// apps/vue/views/RouteClient/TopLevel/Blob.vue
<script setup>
import route from "@/routes/route-client/blob";

const response = await route.post({
  body: new Blob(["hello"], {
    type: "application/octet-stream"
  }),
});
const result = new TextDecoder().decode(await response.arrayBuffer());
</script>
<template>
  <span id="result">{{ result }}</span>
</template>

// apps/solid/views/RouteClient/TopLevel/Blob.tsx
import route from "@/routes/route-client/blob";

const response = await route.post({
  body: new Blob(["hello"], {
    type: "application/octet-stream",
  }),
});
const result = new TextDecoder().decode(await response.arrayBuffer());

export default function TopLevelBlob() {
  return <span id="result">{result}</span>;
}
