// packages/react/src/private/create-root.ts
export default (length: number, i18n_active: boolean) => {
  const n = length - 1;
  const body = Array.from({ length: n }, (_, i) => i - 1)
    .reduceRight((child, _, i) => `components[${i + 1}] !== undefined
        ? createElement(components[${i}], {request, ...props[${i}]}, ${child})
        : createElement(components[${i}], {request, ...props[${i}]})
    `, `createElement(components[${n}], {request, ...props[${n}]})`);

  const i18n_imports = i18n_active
    ? `
      import I18nBridge from "@primate/react/i18n/Bridge";
      import t from "#i18n";`
    : "";

  const tree = i18n_active
    ? `createElement(I18nBridge, { t }, ${body})`
    : body;

  return `
    import { createElement, useState } from "react";
    import AppContext from "@primate/react/context/app";
    import HeadContext from "@primate/react/context/head";
    import platform from "@primate/react/platform";${i18n_imports}

    export default ({
      components,
      props,
      request,
      push_heads: value,
    }) => {
      const [context, setContext] = useState(request.context);
      const $value = { context, setContext };
      const tree = ${tree};

      return platform === "browser"
        ? createElement(AppContext.Provider, { value: $value }, tree)
        : createElement(AppContext.Provider, { value: $value },
            createElement(HeadContext.Provider, { value }, tree))
      ;
    }
  `;
};

// packages/solid/src/private/create-root.ts
export default (length: number, i18n_active: boolean) => {
  const n = length - 1;
  const body = Array.from({ length: n }, (_, i) => i - 1)
    .reduceRight((child, _, i) => `components[${i + 1}] !== undefined
        ? createComponent(components[${i}], {request, ...props[${i}],
            children: ${child}})
        : createComponent(components[${i}], {request, ...props[${i}]})
    `, `createComponent(components[${n}], {request, ...props[${n}]})`);

  const i18n_imports = i18n_active
    ? `
      import I18nBridge from "@primate/solid/i18n/Bridge";
      import t from "#i18n";`
    : "";

  const tree = i18n_active
    ? `<I18nBridge t={t}>{${body}}</I18nBridge>`
    : `{${body}}`;

  return `
    import { createSignal } from "solid-js";
    import { createComponent } from "solid-js/web";
    import AppContext from "@primate/solid/context/app";
    import HeadContext from "@primate/solid/context/head";${i18n_imports}

    export default ({
      components,
      props,
      request,
      push_heads: value,
    }) => {
      const [context, setContext] = createSignal(request.context);
      const $value = { context, setContext };

      return <AppContext.Provider value={$value}>
          <HeadContext.Provider value={value}>
            ${tree}
          </HeadContext.Provider>
        </AppContext.Provider>
    }
  `;
};
