// apps/solid/views/RouteClient/ActionRedirect.tsx
import route from "@/routes/route-client/action-redirect";
import client from "@primate/solid/client";

export default function ClientRouteActionRedirect() {
  const form = client.form(route.post);

  return <form id={form.id} onSubmit={form.submit}>
    <button id="send" type="submit">Send</button>
  </form>;
}

// apps/angular/views/RouteClient/ActionRedirect.component.ts
import route from "@/routes/route-client/action-redirect";
import type { OnInit } from "@angular/core";
import { Component } from "@angular/core";
import client from "@primate/angular/client";

@Component({
  template: `
    @if (form) {
      <form [id]="form.id" (submit)="form.submit($event)">
        <button id="send" type="submit">Send</button>
      </form>
    }
  `,
})
export default class ActionComponent implements OnInit {
  form!: ReturnType<typeof client.form>;

  ngOnInit() {
    this.form = client.form(route.post);
  }
}
