// apps/vue/views/RouteClient/Blob.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/blob";

const result = ref(null);

async function send() {
  const body = new Blob(["hello"], { type: "application/octet-stream" });
  const response = await route.post({ body });
  result.value = new TextDecoder().decode(await response.arrayBuffer());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>

// apps/svelte/views/RouteClient/Blob.svelte
<script>
  import route from "@/routes/route-client/blob";
  let result = $state(null);
  async function send() {
    const body = new Blob(["hello"], { type: "application/octet-stream" });
    const response = await route.post({ body });
    result = new TextDecoder().decode(await response.arrayBuffer());
  }
</script>

<button onclick={send}>Send</button>
{#if result !== null}
  <span id="result">{result}</span>
{/if}
