// apps/vue/views/RouteClient/Form.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/form";

const result = ref(null);

async function send() {
  const response = await route.post({ body: new URLSearchParams({ foo: "bar" }) });
  result.value = JSON.stringify(await response.json());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>

// apps/svelte/views/RouteClient/Form.svelte
<script>
  import route from "@/routes/route-client/form";
  let result = $state(null);
  async function send() {
    const response = await route.post({
      body: new URLSearchParams({ foo: "bar" }),
    });
    result = await response.json();
  }
</script>

<button onclick={send}>Send</button>
{#if result !== null}
  <span id="result">{JSON.stringify(result)}</span>
{/if}
