// apps/vue/views/RouteClient/JSON.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/json";

const result = ref(null);

async function send() {
  const response = await route.post({ body: { foo: "bar" } });
  result.value = JSON.stringify(await response.json());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>

// apps/svelte/views/RouteClient/JSON.svelte
<script>
  import route from "@/routes/route-client/json";

  let result = $state(null);

  async function send() {
    const response = await route.post({ body: { foo: "bar" } });
    result = await response.json();
  }
</script>

<button onclick={send}>Send</button>
{#if result !== null}
  <span id="result">{JSON.stringify(result)}</span>
{/if}
