// apps/svelte/views/Redirect.svelte
<script lang="ts">
  import client from "@primate/svelte/client";

  const form = client.form({ initial: { email: "" } });
</script>

{#if $form.submitted}
  <p id="submitted">submitted</p>
{:else}
  <form method="post" id={$form.id} onsubmit={$form.submit}>
    <button type="submit">Submit</button>
  </form>
{/if}

// apps/react/views/Redirect.tsx
import { client } from "@primate/react";

export default function Redirect() {
  const form = client.form({ initial: { email: "" } });

  if (form.submitted) return <p id="submitted">submitted</p>;

  return (
    <form method="post" id={form.id} onSubmit={form.submit}>
      <button type="submit">Submit</button>
    </form>
  );
}
