// apps/vue/views/Submit.vue
<script setup lang="ts">
import { client } from "@primate/vue";

const form = client.form({ initial: { email: "" } });
</script>

<template>
  <p v-if="form.submitted" id="submitted">submitted</p>
  <form v-else method="post" :id="form.id" @submit="form.submit">
    <button type="submit">Submit</button>
  </form>
</template>

// apps/react/views/Submit.tsx
import client from "@primate/react/client";

export default function Submit() {
  const form = client.form({ initial: { email: "" } });

  if (form.submitted) return <p id="submitted">submitted</p>;

  return (
    <form method="post" id={form.id} onSubmit={form.submit}>
      <button type="submit">Submit</button>
    </form>
  );
}
