// apps/react/views/i18n/Index.tsx
import t from "#lib/i18n";

export default function I18NIndex() {
  return <>
    <span id="locale">{t.locale.get()}</span>
    <span id="title">{t("title")}</span>
    <button id="de" onClick={() => t.locale.set("de-DE")}>
      {t("german")}
    </button>
    <button id="en" onClick={() => t.locale.set("en-US")}>
      {t("english")}
    </button>
  </>;
}

// apps/angular/views/i18n/Index.component.ts
import t from "@/lib/i18n";
import { Component } from "@angular/core";

@Component({
  template: `
    <span id="locale">{{ t.locale.get() }}</span>
    <span id="title">{{ t("title") }}</span>
    <button id="de" (click)="t.locale.set('de-DE')">{{ t("german") }}</button>
    <button id="en" (click)="t.locale.set('en-US')">{{ t("english") }}</button>
  `,
})
export default class I18nIndex {
  t = t;
}
