// apps/svelte/views/RouteClient/Action.svelte
<script>
  import route from "@/routes/route-client/action";
  import client from "@primate/svelte/client";

  const form = client.form(route.post);
</script>

<form id={$form.id} onsubmit={$form.submit}>
  <input id="foo" name="foo" />
  <button id="send" type="submit">Send</button>
  {#if $form.submitted}
    <span id="result">{JSON.stringify({ foo: "hello" })}</span>
  {/if}
  {#if $form.field("foo").error}
    <span id="error">{$form.field("foo").error}</span>
  {/if}
</form>

// apps/vue/views/RouteClient/Action.vue
<script setup>
import route from "@/routes/route-client/action";
import client from "@primate/vue/client";

const form = client.form(route.post);
</script>

<template>
  <form :id="form.id" @submit="form.submit">
    <input id="foo" name="foo" />
    <button id="send" type="submit">Send</button>
    <span v-if="form.submitted" id="result">{{ JSON.stringify({ foo: "hello" }) }}</span>
    <span v-if="form.field('foo').error" id="error">{{ form.field('foo').error }}</span>
  </form>
</template>
