// apps/svelte/views/RouteClient/FormLevel.svelte
<script>
  import route from "@/routes/route-client/form-level";
  import client from "@primate/svelte/client";

  const form = client.form(route.post);
</script>

<form id={$form.id} onsubmit={$form.submit}>
  <input id="foo" name="foo" />
  <button id="send" type="submit">Send</button>
  {#if $form.submitted}<span id="result">ok</span>{/if}
  {#if $form.errors.length > 0}<span id="error">{$form.errors[0]}</span>{/if}
</form>

// apps/vue/views/RouteClient/FormLevel.vue
<script setup>
import route from "@/routes/route-client/form-level";
import client from "@primate/vue/client";

const form = client.form(route.post);
</script>

<template>
  <form :id="form.id" @submit="form.submit">
    <input id="foo" name="foo" />
    <button id="send" type="submit">Send</button>
    <span v-if="form.submitted" id="result">ok</span>
    <span v-if="form.errors.length > 0" id="error">{{ form.errors[0] }}</span>
  </form>
</template>
