// apps/react/views/RouteClient/JSON.tsx
import route from "@/routes/route-client/json";
import { useState } from "react";

export default function ClientRouteJSON() {
  const [result, setResult] = useState<string | null>(null);

  async function send() {
    const response = await route.post({ body: { foo: "bar" } });
    setResult(JSON.stringify(await response.json()));
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result !== null && <span id="result">{result}</span>}
    </>
  );
}

// apps/vue/views/RouteClient/JSON.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/json";

const result = ref(null);

async function send() {
  const response = await route.post({ body: { foo: "bar" } });
  result.value = JSON.stringify(await response.json());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>
