// apps/svelte/views/RouteClient/Text.svelte
<script>
  import route from "@/routes/route-client/text";

  let result = $state(null);

  async function send() {
    const response = await route.post({ body: "hello" });
    result = await response.text();
  }
</script>

<button onclick={send}>Send</button>
{#if result !== null}
  <span id="result">{result}</span>
{/if}

// apps/vue/views/RouteClient/Text.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/text";

const result = ref(null);

async function send() {
  const response = await route.post({ body: "hello" });
  result.value = await response.text();
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>
