// apps/react/views/RouteClient/Text.tsx
import route from "@/routes/route-client/text";
import { useState } from "react";

export default function ClientRouteText() {
  const [result, setResult] = useState<string | null>(null);

  async function send() {
    const response = await route.post({ body: "hello" });
    setResult(await response.text());
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result !== null && <span id="result">{result}</span>}
    </>
  );
}

// apps/vue/views/RouteClient/Text.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/text";

const result = ref(null);

async function send() {
  const response = await route.post({ body: "hello" });
  result.value = await response.text();
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>
