// apps/angular/views/ViewPost.component.ts
import t from "#i18n";
import { Component, Input } from "@angular/core";

@Component({
  template: `
    <h1>{{ t("title") }}: {{ post.title }}</h1>
    <div>Id: {{ post.id }}</div>
    <h3>{{ t("switch_language") }}</h3>
    <button (click)="setLocale('en-US')">{{ t("english") }}</button>
    <button (click)="setLocale('de-DE')">{{ t("german") }}</button>
  `,
})
export default class PostDetail {
  @Input() post: any;

  t = t;

  setLocale(locale: string) {
    t.locale.set(locale);
  }
}

// apps/svelte/components/ViewPost.svelte
<script>
  import t from "#i18n";

  export let post;
</script>

<h1>{$t("title")}: {post.title}</h1>

<div>Id: {post.id}</div>
<h3>{$t("switch_language")}</h3>
<button on:click={() => t.locale.set("en-US")}>{$t("english")}</button>
<button on:click={() => t.locale.set("de-DE")}>{$t("german")}</button>
