// apps/react/views/Form.tsx
import client from "@primate/react/client";

interface Props { counter: number; id: number };

export default function Form(props: Props) {
  const form = client.form({ initial: { counter: props.counter } });

  return <form
    method="post"
    action={`/form?id=${props.id}`}
    id={form.id}
    onSubmit={form.submit}
  >
    {form.errors.length > 0
      ? <p style={{ color: "red" }}>{form.errors[0]}</p>
      : ""
    }
    <label>
      Counter:
      <input
        type="number"
        name={form.field("counter").name}
        defaultValue={form.field("counter").value}
      />
    </label>
    {form.field("counter").error
      ? <p id="counter-error" style={{ color: "red" }}>{form.field("counter").error}</p>
      : ""
    }
    {form.submitted && <span id="submitted">saved</span>}
    <button type="submit" disabled={form.submitting}>Save</button>
  </form>;
}

// apps/vue/views/Form.vue
<script setup lang="ts">
import { client } from "@primate/vue";

interface Props { counter: number; id: number }
const props = defineProps<Props>();

const form = client.form({ initial: { counter: props.counter } });
</script>

<template>
  <form
    :id="form.id"
    method="post"
    :action="`/form?id=${props.id}`"
    @submit="form.submit"
  >
    <p v-if="form.errors.length" style="color: red">{{ form.errors[0] }}</p>

    <label>
      Counter:
      <input
        v-once
        type="number"
        :name="form.field('counter').name"
        :value="form.field('counter').value"
      />
    </label>

    <p v-if="form.field('counter').error" id="counter-error" style="color: red">
      {{ form.field('counter').error }}
    </p>

    <p v-if="form.submitted"><span id="submitted">saved</span></p>
    <button type="submit" :disabled="form.submitting">Save</button>
  </form>
</template>
