// apps/solid/views/RouteClient/TopLevel/Multipart.tsx
import route from "@/routes/route-client/multipart";

const body = new FormData();
body.append("foo", "bar");
body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
const response = await route.post({ body });
const result = await response.json();

export default function TopLevelMultipart() {
  return <span id="result">{JSON.stringify(result)}</span>;
}

// apps/svelte/views/RouteClient/TopLevel/Multipart.svelte
<script>
  import route from "@/routes/route-client/multipart";

  const body = new FormData();
  body.append("foo", "bar");
  body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
  const response = await route.post({ body });
  const result = await response.json();
</script>

<span id="result">{JSON.stringify(result)}</span>
