// packages/react/src/private/i18n/Bridge.browser.tsx
import AppContext from "#context/app";
import type { API, Catalogs } from "@primate/core/i18n";
import { internal } from "@primate/core/i18n";
import type { ReactNode } from "react";
import { useContext, useEffect } from "react";

export default function I18nBridge<C extends Catalogs>(
  { t, children }: { t: API<C>; children?: ReactNode },
) {
  const { context, setContext } = useContext(AppContext);
  const server = context.i18n.locale;
  if (server !== undefined && server !== t.locale.get()) {
    t[internal].init(server);
  }

  useEffect(() => { t[internal].restore(); }, []);

  useEffect(() => t.subscribe(() => {
    setContext(prev => ({
      ...prev,
      i18n: { ...prev.i18n, locale: t.locale.get() },
    }));
  }), [setContext, t]);

  return <>{children}</>;
}

// packages/solid/src/private/i18n/Bridge.browser.tsx
import AppContext from "#context/app";
import type { API, Catalogs } from "@primate/core/i18n";
import { internal } from "@primate/core/i18n";
import type { JSX } from "solid-js";
import { createSignal, onCleanup, onMount, useContext } from "solid-js";

export default function I18nBridge<C extends Catalogs>(
  props: { t: API<C>; children?: JSX.Element },
) {
  const { context } = useContext(AppContext);
  const server = context().i18n.locale;
  if (server !== undefined && server !== props.t.locale.get()) {
    props.t[internal].init(server);
  }

  // tick when locale changes
  const [version, setVersion] = createSignal(props.t[internal].version);

  const removeDepend = props.t[internal].depend(() => { version(); });

  const off = props.t.subscribe(() => setVersion(v => v + 1));

  onMount(() => props.t[internal].restore());

  onCleanup(() => {
    off();
    removeDepend();
  });

  return <>{props.children}</>;
}
