// apps/svelte/views/Submit.svelte
<script lang="ts">
  import { client } from "@primate/svelte";

  const form = client.form({ initial: { email: "" } });
</script>

{#if $form.submitted}
  <p id="submitted">submitted</p>
{:else}
  <form method="post" id={$form.id} onsubmit={(e) => $form.submit(e)}>
    <button type="submit">Submit</button>
  </form>
{/if}

// packages/solid/fixtures/views/Submit.tsx
import client from "@primate/solid/client";

export default function Submit() {
  const form = client.form({ initial: { email: "" } });

  return (
    <>
      {form.submitted ? (
        <p id="submitted">submitted</p>
      ) : (
        <form method="post" id={form.id} onSubmit={form.submit}>
          <button type="submit">Submit</button>
        </form>
      )}
    </>
  );
}
