// apps/solid/views/RouteClient/TopLevel/Blob.tsx
import route from "@/routes/route-client/blob";

const response = await route.post({
  body: new Blob(["hello"], {
    type: "application/octet-stream",
  }),
});
const result = new TextDecoder().decode(await response.arrayBuffer());

export default function TopLevelBlob() {
  return <span id="result">{result}</span>;
}

// apps/angular/views/RouteClient/TopLevel/Blob.component.ts
import route from "@/routes/route-client/blob";
import { Component } from "@angular/core";

const response = await route.post({
  body: new Blob(["hello"], {
    type: "application/octet-stream",
  }),
});
const result = new TextDecoder().decode(await response.arrayBuffer());

@Component({
  template: `<span id="result">{{ result }}</span>`,
})
export default class TopLevelBlob {
  result = result;
}
