// apps/solid/views/RouteClient/TopLevel/Multipart.tsx
import route from "@/routes/route-client/multipart";

const body = new FormData();
body.append("foo", "bar");
body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
const response = await route.post({ body });
const result = await response.json();

export default function TopLevelMultipart() {
  return <span id="result">{JSON.stringify(result)}</span>;
}

// apps/angular/views/RouteClient/TopLevel/Multipart.component.ts
import route from "@/routes/route-client/multipart";
import { Component } from "@angular/core";

const body = new FormData();
body.append("foo", "bar");
body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
const response = await route.post({ body });
const result = JSON.stringify(await response.json());

@Component({
  template: `<span id="result">{{ result }}</span>`,
})
export default class TopLevelMultipart {
  result: string = result;
}
