// apps/react/views/Submit.tsx
import client from "@primate/react/client";

export default function Submit() {
  const form = client.form({ initial: { email: "" } });

  if (form.submitted) return <p id="submitted">submitted</p>;

  return (
    <form method="post" id={form.id} onSubmit={form.submit}>
      <button type="submit">Submit</button>
    </form>
  );
}

// packages/svelte/fixtures/views/Submit.svelte
<script lang="ts">
  import client from "@primate/svelte/client";
  const form = client.form({ initial: { email: "" } });
</script>

{#if $form.submitted}
  <p id="submitted">submitted</p>
{:else}
  <form method="post" id={$form.id} onsubmit={(e) => $form.submit(e)}>
    <button type="submit">Submit</button>
  </form>
{/if}
