// apps/svelte/views/RouteClient/Action.svelte
<script>
  import route from "@/routes/route-client/action";
  import client from "@primate/svelte/client";

  const form = client.form(route.post);
</script>

<form id={$form.id} onsubmit={$form.submit}>
  <input id="foo" name="foo" />
  <button id="send" type="submit">Send</button>
  {#if $form.submitted}
    <span id="result">{JSON.stringify({ foo: "hello" })}</span>
  {/if}
  {#if $form.field("foo").error}
    <span id="error">{$form.field("foo").error}</span>
  {/if}
</form>

// apps/react/views/RouteClient/Action.tsx
import route from "@/routes/route-client/action";
import client from "@primate/react/client";

export default function ClientRouteAction() {
  const form = client.form(route.post);

  return <form id={form.id} onSubmit={form.submit}>
    <input id="foo" name="foo" />
    <button id="send" type="submit">Send</button>
    {form.submitted && <span id="result">{JSON.stringify({ foo: "hello" })}</span>}
    {form.field("foo").error && <span id="error">{form.field("foo").error}</span>}
  </form>;
}
