// apps/vue/views/RouteClient/Form.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/form";

const result = ref(null);

async function send() {
  const response = await route.post({ body: new URLSearchParams({ foo: "bar" }) });
  result.value = JSON.stringify(await response.json());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>

// apps/react/views/RouteClient/Form.tsx
import route from "@/routes/route-client/form";
import { useState } from "react";

export default function ClientRouteForm() {
  const [result, setResult] = useState<string | null>(null);

  async function send() {
    const body = new URLSearchParams({ foo: "bar" });
    const response = await route.post({ body });
    setResult(JSON.stringify(await response.json()));
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result !== null && <span id="result">{result}</span>}
    </>
  );
}
