// apps/solid/views/RouteClient/JSON.tsx
import route from "@/routes/route-client/json";
import { createSignal } from "solid-js";

export default function RouteClientJSON() {
  const [result, setResult] = createSignal<string | null>(null);

  async function send() {
    const response = await route.post({ body: { foo: "bar" } });
    setResult(JSON.stringify(await response.json()));
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result() !== null && <span id="result">{result()}</span>}
    </>
  );
}

// apps/react/views/RouteClient/JSON.tsx
import route from "@/routes/route-client/json";
import { useState } from "react";

export default function ClientRouteJSON() {
  const [result, setResult] = useState<string | null>(null);

  async function send() {
    const response = await route.post({ body: { foo: "bar" } });
    setResult(JSON.stringify(await response.json()));
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result !== null && <span id="result">{result}</span>}
    </>
  );
}
