// apps/vue/views/RouteClient/Multipart.vue
<script setup>
import { ref } from "vue";
import route from "@/routes/route-client/multipart";

const result = ref(null);

async function send() {
  const body = new FormData();
  body.append("foo", "bar");
  body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
  const response = await route.post({ body });
  result.value = JSON.stringify(await response.json());
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ result }}</span>
</template>

// apps/react/views/RouteClient/Multipart.tsx
import route from "@/routes/route-client/multipart";
import { useState } from "react";

export default function ClientRouteMultipart() {
  const [result, setResult] = useState<string | null>(null);

  async function send() {
    const body = new FormData();
    body.append("foo", "bar");
    body.append("file", new File(["hello"], "hello.txt", { type: "text/plain" }));
    const response = await route.post({ body });
    setResult(JSON.stringify(await response.json()));
  }

  return (
    <>
      <button onClick={send}>Send</button>
      {result !== null && <span id="result">{result}</span>}
    </>
  );
}
