// apps/vue/views/RouteClient/OptionalPath.vue
<script setup lang="ts">
import route from "@/routes/route-client/optional-path/[[name]]";
import { ref } from "vue";

const result = ref(null);
const { name } = defineProps<{ name: string }>();

async function send() {
  const response = await route.post({ path: { name } });
  result.value = await response.json();
}
</script>

<template>
  <button @click="send">Send</button>
  <span v-if="result !== null" id="result">{{ JSON.stringify(result) }}</span>
</template>

// apps/react/views/RouteClient/OptionalPath.tsx
import route from "@/routes/route-client/optional-path/[[name]]";
import { useState } from "react";

export default function Path(props: { name: string }) {
  const [result, setResult] = useState(null);

  async function send() {
    const response = await route.post({ path: { name: props.name } });
    setResult(await response.json());
  }

  return <>
    <button onClick={send}>Send</button>
    {result !== null && <span id="result">{JSON.stringify(result)}</span>}
  </>;
}
