// apps/angular/views/RouteClient/PathAction.component.ts
import route from "@/routes/route-client/path-action/[name]";
import type { OnInit } from "@angular/core";
import { Component, input } from "@angular/core";
import client from "@primate/angular/client";

@Component({
  template: `
    <form [id]="form.id" (submit)="form.submit($event)">
      <input id="foo" name="foo" />
      <button id="send" type="submit">Send</button>
      @if (form.submitted()) {
        <span id="result">{{ stringify(form.result()) }}</span>
      }
      @if (form.field('foo').error()) {
        <span id="error">{{ form.field('foo').error() }}</span>
      }
    </form>
  `,
})
export default class PathAction implements OnInit {
  name = input.required<string>();
  form!: ReturnType<typeof client.form>;
  stringify = JSON.stringify;

  ngOnInit() {
    this.form = client.form(route.post, { path: { name: this.name() } });
  }
}

// apps/react/views/RouteClient/PathAction.tsx
import route from "@/routes/route-client/path-action/[name]";
import client from "@primate/react/client";

export default function PathAction({ name }: { name: string }) {
  const form = client.form(route.post, { path: { name } });
  return (
    <form id={form.id} onSubmit={form.submit}>
      <input id="foo" name="foo" />
      <button id="send" type="submit">Send</button>
      {form.submitted && <span id="result">{JSON.stringify(form.result)}</span>}
      {form.field("foo").error && <span id="error">{form.field("foo").error}</span>}
    </form>
  );
}
