// apps/svelte/views/RouteClient/Path.svelte
<script>
  import route from "@/routes/route-client/path/[name]";
  let result = $state(null);
  const { name } = $props();

  async function send() {
    const response = await route.post({ path: { name } });
    result = await response.json();
  }
</script>

<button onclick={send}>Send</button>
{#if result !== null}
  <span id="result">{JSON.stringify(result)}</span>
{/if}

// apps/react/views/RouteClient/Path.tsx
import route from "@/routes/route-client/path/[name]";
import { useState } from "react";

export default function Path(props: { name: string }) {
  const [result, setResult] = useState(null);

  async function send() {
    const response = await route.post({ path: { name: props.name } });
    setResult(await response.json());
  }

  return <>
    <button onClick={send}>Send</button>
    {result !== null && <span id="result">{JSON.stringify(result)}</span>}
  </>;
}
